version: '3.4'

services:
  vnexpressdatawarehouse:
    image: vnexpressdatawarehouse
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 vnexpress_data_warehouse/spiders/TTTThao_feature_crawl.py "]
    ports:
      - 5678:5678
